name: which-key-test
on:
  pull_request:
  push:
    branches:
      - master
  schedule:
    - cron: '0 0 1 * *'

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        emacs_version:
          - 25.1
          - 25.2
          - 25.3
          - 26.1
          - 26.2
          - 26.3
          - snapshot
    steps:
    - uses: purcell/setup-emacs@master
      with:
        version: ${{ matrix.emacs_version }}

    - uses: actions/checkout@v2
    - name: Run tests
      run: 'emacs -Q -batch -L . -l which-key-tests.el -f ert-run-tests-batch-and-exit'
